import numpy as np
import random
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

#calcoli
arr_array= np.array([1,2,3,4,5,6])
arr_array2= np.array([7,8,9,10,11,12])
arr_array.shape
arr=[1,2,3,4]
arr_zero = np.zeros([2,3,4])
arr_one = np.ones([2,3,4])
arr_full = np.full([3,4,5],5)
arr_arange= np.arange(5,1005,5)
arr_empty= np.empty([5,5,5])
arr_append= np.append(arr,[5,6,7,8,9])
arr_insert = np.insert(arr_append,5,[6,7,8,9])
arr_sort = np.sort(arr)[::-1]
arr_concatenate =np.concatenate((arr_array,arr_array2),axis=0)
arr_stack=np.stack((arr_array,arr_array2))
arr_hstack=np.hstack((arr_array,arr_array2))
arr_vstack=np.vstack((arr_array,arr_array2))
arr_sum=np.sum(arr_array)
arr_prod=np.prod(arr_array)
arr_div=arr_array2 / arr_array
arr_sottr=arr_array2 - arr_array
arr_cos=np.cos(arr_array)
arr_sqrt = np.sqrt(arr_array)
arr_mean=np.mean(arr_array)
arr_log = np.log10(arr_array)
arr_median = np.median(arr_array)
arr_max=np.max(arr_array)
arr_min = np.min(arr_array)
arr_argmax = np.argmax(arr_array)
arr_argmin=np.argmin(arr_array)
arr_sort2 = np.sort(arr_array)
arr_std = np.std(arr_array)
arr_randomrandint = np.random.randint(0,100,size=(5,6,7))
arr_randomchoice = np.random.choice([10,20,30])
arr_randomnormal= np.random.normal(loc=170,scale=2,size=(3,5,6))

#output
print(arr)
print(arr_sort)
print(arr_zero)
print(arr_one)
print(arr_full)
print(arr_arange)
print(arr_empty)
print(arr_append)
print(np.delete(arr,2))
print(arr_insert)
print(arr_array.flatten())
print(arr_array.ravel())
print(arr_array.transpose())
print(arr_array.swapaxes(0,0))
print(arr_concatenate)
print(arr_stack)
print(arr_hstack)
print(arr_vstack)
print(np.split(arr_array,2,axis=0))
print(arr_array)
print(arr_sum)
print(arr_prod)
print(arr_div)
print(arr_sottr)
print(arr_cos)
print(arr_sqrt)
print(arr_mean)
print(arr_median)
print(arr_min)
print(arr_max)
print(arr_argmax)
print(arr_argmin)
print(arr_log)
print(arr_sort2)
print(arr_std)
print(arr_randomrandint)
print(arr_randomchoice)
print(arr_randomnormal)

#grafico
arange=np.arange(-10,10,0.2)
arangey=np.arange(-10,10,0.2)
x,y=np.meshgrid(arange,arangey)
animation= np.sin(x) * np.sin(y)
ax = plt.axes(projection="3d",facecolor="Black")
ax.plot_surface(x,y,animation,cmap="plasma")
ax.set_xlim(0.50)
ax.set_ylim(0,100)
ax.set_title("Array")
ax.set_ylabel("Y",color="White")
plt.grid(True,linestyle="--",color="Gray",alpha=0.5)
ax.set_xlabel("x",color="White")
plt.show()
